#!/bin/bash

#SBATCH -t 1:00:00

#SBATCH -n 24

#SBATCH -p short



#Load modules

module load eb

module load Miniconda2

# loading virtualenv

source activate qiime1

# setting temporary directory

export TMPDIR=~/qiime_tmp

# make otu network
echo "make otu network"
time make_otu_network.py -i /home/cbmucl39/2018_02_smb/Diversityanalysis/tax/otu_table_L2.biom -m ~/2018_02_smb/mappingfile.tsv -o phyla_otu_network

# deactivate
source deactivate
